# Generated by Django 3.1.3 on 2020-11-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_enrollment', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Matrícula_estudiante')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('photography', models.ImageField(upload_to='estudiante', verbose_name='Foto')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.grade')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name'],
                'unique_together': {('student_enrollment', 'first_name', 'last_name', 'grade')},
            },
        ),
    ]
