# Generated by Django 3.1.3 on 2020-11-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photography',
            field=models.ImageField(upload_to='students', verbose_name='Foto'),
        ),
    ]
