# Generated by Django 3.1.3 on 2020-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de usuario')),
            ],
            options={
                'verbose_name': 'User type',
                'verbose_name_plural': 'User types',
                'ordering': ['id'],
            },
        ),
    ]
