# Generated by Django 3.1.3 on 2020-11-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_card', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='DNI')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=9, verbose_name='Telefono')),
                ('user', models.CharField(max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_type.usertype')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['last_name'],
                'unique_together': {('id_card', 'first_name', 'last_name', 'phone', 'user', 'password', 'user_type')},
            },
        ),
    ]
